# -*- coding: utf-8 -*-
"""RandomPassword.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GrtNtk_gzFwzknzfHpMnLNUr5S-MxkfM
"""

import string
import secrets
alphabet = string.ascii_letters + string.digits + string.hexdigits
password = ''.join(secrets.choice(alphabet) for i in range(16))

print(password)